name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            set-safe-directory: ..
            path: ./blender
      - name: configure
        run: sudo apt update && sudo apt install -y build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev
      - name: lib files
        run: mkdir lib && cd lib && svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_x86_64_glibc_228
        working-directory: .
      # - name: make update
      #   run: make update
      - name: make
        run: make
        working-directory: ./blender
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
